# Generated by Django 5.2.12 on 2026-03-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_secciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_secciones.seccion')),
            ],
        ),
    ]
